title: Matthew Lim
logo: "/images/mlim.jpg?raw=true"
description: >
  Hi there! I'm a data and analytics professional with over eight years of experience in driving business growth through data-driven insights.
  I have a proven track record of collaborating with cross-functional teams and leading teams to deliver impactful results. With expertise in SQL dialects (most recently Snowflake), dbt, and visualization tools (most recently Looker), 
  I transform complex data challenges to deliver actionable insights. I'm passionate about building scalable data assets, mentoring others, and fostering a culture of continuous improvement.
  <br><br>
  <a href="https://www.linkedin.com/in/matthewklim/">LinkedIn Profile</a> 
  
markdown: kramdown
google_analytics: G-WRVE5934HY
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
